### ISSUE TITLE
Can't find definition of single_observation_space

### ISSUE THREAD

**Issue by Zhang-wenpeng** [Manaro-Alpha/Obstacle-Avoidance-using-RL#1]
I find envs.single_observation_space in PPO_continuous.py but can't find it's definition. In ObsAv_Env.py ,self.observation_space is a dict ,how to input a dict into nn.Linear()?

**Comment by Manaro-Alpha** [comment]
Hi,
I am not inputting a dictionary into nn.linear rather shape of the observation_space(). To learn more about gym.spaces, please look at the gym documentation and source code.
Cheers.
